### ISSUE TITLE
mathicsscript error

### ISSUE THREAD

**Issue by wuyudi** [mathics/Mathics#1156]
On win, if run mathicsscript.exe

```bash
runpy.py 194 _run_module_as_main
return _run_code(code, main_globals, None,

runpy.py 87 _run_code
exec(code, run_globals)

__main__.py 4 <module>
from mathicsscript.__main__ import main

__main__.py 11 <module>
from mathicsscript.termshell import ShellEscapeException, TerminalShell

termshell.py 49 <module>
from readline import (

ModuleNotFoundError:
No module named 'readline'
```

according to this:

https://stackoverflow.com/a/51964654/13040423

add

```py
from pyreadline import Readline

readline = Readline()
```

to termshell.py 
![image](https://user-images.githubusercontent.com/30024051/108168172-cf49f980-7131-11eb-8864-f6681ec3a0b1.png)

bug fix.

**Comment by rocky** [comment]
Hmm.  The `readline` module [is part of the Python standard library in 3.6](https://docs.python.org/3.6/library/readline.html) and up so I am wondering how is it that you don't have this? 

I fired up my Windows 10 box and tried running a powershell session and I was able to import all of the realline functions that were imported and everything worked for me there. 

Some information on your environment and Python version and how it comes to be that you don't have the readline module is needed to decide if anything is needed here. Otherwise, I'll close this.

**Comment by wuyudi** [comment]
Python 3.8.5 x32
win10

I use git bash at the beginning, just now I tried PowerShell, it works well. And autocomplete works well with PS, on git bash, it doesn't work.

**Comment by rocky** [comment]
@wuyudi recently I have been working on getting the fancier command-line shell [`mathicsscript`](https://pypi.org/project/mathicsscript/) to make it more robust and work in more environments. 

If there are some environments where mathicsscript doesn't work and can be made to work by using another method like pyreadline for readline, then I'd consider them - especially if someone else wants to contribute to this.
