### ISSUE TITLE
Images are broken

### ISSUE THREAD

**Issue by rocky** [mathics/Mathics#1434]
In converting to new MathJax images became broken. 

For example: 

```
Import["ExampleData/lena.tif"]
```

@TiagoCavalcanteTrindade  is this of interest to you?

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky I saw that in mathicsscript the image MathML form looks right except by the `b` in the begin of `src`
```html
<math display="block"><mglyph src="b'data:image/png;base64,
```

And the image source is HUGE.

In Mathics Django the image is received, then, because of a bug that I don't know where is, it is sent back, the URI is too long, what breaks the server, and then I need to restart it to go back working.
