### ISSUE TITLE
Django Interface Exception on every input

### ISSUE THREAD

**Issue by egrath** [mathics/Mathics#1499]
In Mathics 3.1.0, running on Python 3.9.5 on Windows, every input in the Django Webinterface results in the following error:
```
System::exception:
Exception raised: 'NoneType' object has no attribute 'replace' 
```
The issue occurs even on a complete fresh Python installation with just Mathics installed by:
```
pip install mathics3-omnibus
```
This issue only occurs on the Webinterface, running a interactive console session works as expected.

**Comment by rocky** [comment]
What's the full Python traceback? 

There will be a release of everything Mathics core and Mathics Django in about a week or so. A lot has changed and some changes are incompatible. So it doesn't surprise me that things are broken in Django.

**Comment by rocky** [comment]
From this, it looks like  the setting file `autoload/settings.m` is not read in. I guess that would be under c:/Users/egonr/AppData/Roaming/Python/Mathics/  but I'll have to check on a Windows box when I have one running. 

This might be a be a packaging problem and I'll look for that.  A new release will be coming up relatively soon, so I will check specifically for these things.

A workaround is to set ``Settings`$QuotedStrings = True``  inside the session.

**Comment by rocky** [comment]
There were basically 2 bugs here. 

* Release 4.0.1 of Mathics-Django should address the problem that settings file wasn't getting loaded. This was a packaging problem
*  https://github.com/mathics/Mathics/pull/1512 addresses the traceback seen here.

Finally, let me say that although there was a weakness in Mathics core, since this was a Django problem that repository probably would have been the better place to report this. Or if you felt this was a mathics-omnibus problem, there is an issue tracker for that as well.
