### ISSUE TITLE
from_python and mpmath

### ISSUE THREAD

**Issue by poke1024** [mathics/Mathics#546]
`import mpmath`
`from mathics.core.expression import from_python`
`type(from_python(mpmath.mpf(1) / mpmath.mpf(3)))`

gives

`<class 'mathics.core.expression.MachineReal'>`

Shouldn't this give a `PrecisionReal`?

**Comment by sn6uv** [comment]
The design of `from_python` is that it assumes its arguments are python basic types i.e. int float complex or iterables thereof. With this design goal the behaviour makes sense to me (although raising a TypeError would be better) since it's treating the argument like a python float.

That said, I've been meaning to remove/cleanup from_python for a while.

What's the context of this?

**Comment by poke1024** [comment]
I came across it while cleaning up https://github.com/mathics/Mathics/pull/461. I'm not using `from_python` anymore there, I just wanted to bring this to your attention.

**Comment by sn6uv** [comment]
Okay thanks. Yes, I'm aware a few issues with `from_python`. It's quite a useful utility but it gets abused.
