### ISSUE TITLE
Use python-prompt-toolkit for REPL

### ISSUE THREAD

**Issue by lschumm** [mathics/Mathics#723]
As of yet, the default REPL is super buggy and doesn't support default keybindings (C-a, C-e) or a vi/vim mode. prompt-toolkit, in addition to being vastly more full-featured, is a maintained platform for making interactive prompts; adopting this would mean that the Mathics team would not have to maintain a cross-platform terminal interface in addition to the core code.

**Comment by rocky** [comment]
Seems pretty simple to do and useful. Would you be willing to do?

**Comment by wolfv** [comment]
one other way would be to implement a jupyter kernel. That would give a free ipython console, as well as the jupyter notebook frontend. I think IMathics has some code to that effect.

**Comment by mmatera** [comment]
Look at this: 
https://github.com/mmatera/iwolfram

I didn't maintain it for a while, but I use it every day with mma, and most of the functionalities work. Some years ago it also worked with my branch of mathics (I needed some functionalities that weren't implemented in the main branch), but with the last upgrades maybe it could be broken.
In any case, I am a big fan of modularity, and I think it would be easy to maintain the graphic interface and the text mode kernel as different projects.

**Comment by mmatera** [comment]
btw, I also have an implementation for the :code: syntax in that project (for the web version only, of course...).

**Comment by rocky** [comment]
In my opinion if @mmatera has this covered as a separate project, then folks should just use that. The project could be added to the mathics organization, but that is up to @mmatera and the organization owners.

Overall, I'd like to see projects spun *out* of here and into their own separate projects. I seem to recall there was another ticket about this. 

For my own part, I'd like to ensure that the parsing and translation there is independent of the specific builtins and packages and front ends.

My thought though was that *after* the next release this would go on. 

For the next release, my feeling is let it all be laden with all the features as it is now (and to some extend had been).  I'd prefer something that was more complete than somehting that is broken up into little parts and people have to add the add-ons to get it to be essentially almost as good as Mathematica 5.

**Comment by rocky** [comment]
> btw, I also have an implementation for the :code: syntax in that project (for the web version only, of course...).

I'll igve iwolfram a try.  If this doesn't support ipython console highlighting or decent terminal handling, I may try fixing and putting in a PR.

**Comment by rocky** [comment]
> one other way would be to implement a jupyter kernel. That would give a free ipython console, as well as the jupyter notebook frontend. I think IMathics has some code to that effect.

While at first I had thought this was the way to go, I now realize that while this may be _ultimately_ the right thing, it may be too hard to do initially, unless there was someone dedicated to it.

Creating a `jupyter` kernel is a bit complex programming task, and once done it also adds complexity since you need to know aobut the wire protocol.  I am coming to learn and appreciate that the Mathics core might need improving in terms of its existing kinds of renderers. 

Adding console highlighting and decient terminal handling is pretty simple to do. In fact I've done it, just not made it publicly available yet.  But in the bigger scheme of things it also has made it easier to think about what kinds of features the mathics core  should provide (without worrying about how to expresss this in jupyter).

**Comment by rocky** [comment]
This has been implemented in [mathicsscript](https://github.com/Mathics3/mathicsscript).
