### ISSUE TITLE
Issue with Mathics installation on macOS Mojave

### ISSUE THREAD

**Issue by adakite** [mathics/Mathics#769]
Hey

I don't know if Mathics is still maintained but I am facing issue when installing it on macOS 10.14 (Mojave). On three different units I got the exact same error message:

> `Cannot uninstall 'sympy'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.`

I tried to remove all of my [ana]-conda distribution, make a clean install but still facing this very error that hinders complete installation of Mathics. 

Is there any workaround for running Mathics on macOS ?

 Thanks

**Comment by adakite** [comment]
Ok I'm replying to my own post. I succeed by installing Mathics through Anaconda. It's working.

**Comment by wolfv** [comment]
Congrats.

**Comment by SebSoGa** [comment]
Hi! I'm facing the same issue that you posted here. 
Tried the command conda install mathics, but it doesn't seem to find mathics. Do I need to change my input to the terminal? 

Cheers

**Comment by DXXS** [comment]
I managed to download and install mathics 1.0 on Mojave, and the server ran, and it evaluated basic expressions ok, but it gave errors when attempting to Plot[].  The error was apparently due to using features requiring NumPy >= 1.10, as the system reports "Python 2.7.10" as the default install, using NumPy 1.8 (and didn't want to upgrade NumPy by itself).  I attempted to install python3, and recompiled, but now when running the server in a browser, evaluating any expression is returning "Sorry, an error occurred while processing your request!" <sigh>.
