### ISSUE TITLE
Update to Sympy 1.6 and python 3.8

### ISSUE THREAD

**Issue by stevenleeS0ht** [mathics/Mathics#799]
The sympy 0.x is too old and there is a lot of bug. And so does python.

It would be good idea if port the Mathics to latest dependencies.

**Comment by GarkGarcia** [comment]
The bugs are a separate issue, most of them wouldn't be fixed by updating SymPy or Python, but this is definitively something that should be done. I'm not familiarized with how python binaries are distributed, so I wont create a PR myself.

Maybe @wolfv could help? I looks like this project is having governance issues, since the last update was made about a year ago (this might take a while to be fixed).

**Comment by GarkGarcia** [comment]
@wolfv I think we should work on merging some long-forgotten PRs, update to the newest version of SymPy and release the changes. Do you agree?

I'm not sure updating to Python 3.8 is a good idea thought. The official Python packages on most Linux package managers are still in version 3.8 (I think).

**Comment by GarkGarcia** [comment]
This was partially fixed by https://github.com/mathics/Mathics/pull/821 and https://github.com/mathics/Mathics/pull/825. We're still not using Python 3.8.

**Comment by rocky** [comment]
I looked at the building with 3.8 a little and the error I got had to do with a feature added in 3,8: position-only arguments in function calls. See [PEP570](https://www.python.org/dev/peps/pep-0570/) for a description of Position-only arguments. 

It appears that Mathics creates its own Python ASTs from a parse, and it is not noting in position-only function signature information (since this is a new concept). Therefore when the AST is compiled, the built-in function [compile](https://docs.python.org/3/library/functions.html#compile) barfs.

**Comment by wolfv** [comment]
@GarkGarcia first of all thanks 1000x for the work you're putting in to maintain Mathics right now! 

I think it would be great to support python 3.8, but it's not a problem if we don't immediately get to it.

I don't think I have the rights to publish a package to PyPI but we can (alternatively) also publish a package to conda-forge.
conda-forge is very cool because it also ships a python interpreter so we are not bound to whatever the distro is doing.

**Comment by GarkGarcia** [comment]
> I looked at the building with 3.8 a little and the error I got had to do with a feature added in 3.8: position-only arguments in function calls. See [PEP570](https://www.python.org/dev/peps/pep-0570/) for a description of Position-only arguments.
> 
> It appears that Mathics creates its own Python ASTs from a parse, and it is not noting in position-only function signature information correctly (since this is a new concept). Therefore when the Matihcs-created AST is compiled, the built-in function [compile](https://docs.python.org/3/library/functions.html#compile) barfs.

I'll investigate this. As stated in https://github.com/mathics/Mathics/issues/799#issuecomment-680887859 I'm concerned about updating to Python 3.8, but as long as the change is backward-compatible (ie. Mathics still runs in Python 3.6 and 3.7) I'm fine with it.

> @GarkGarcia first of all thanks 1000x for the work you're putting in to maintain Mathics right now!

No problem 😁️

> I don't think I have the rights to publish a package to PyPI but we can (alternatively) also publish a package to conda-forge.
conda-forge is very cool because it also ships a python interpreter so we are not bound to whatever the distro is doing.

I think it would be better if we could publish an update to PyPI, since this is the defacto standard for Python packages. Maybe we could try to contact @sn6uv (who is the official package maintainer) to ask him to transfer the publishing rights to any of the current maintainers, but he haven't answered to any of my contact-attempts for about a month now.

**Comment by GarkGarcia** [comment]
Fixed in https://github.com/mathics/Mathics/commit/53988e8fb6501bbd0913b4f6c38e020f5ab495b9
