### ISSUE TITLE
Use Github Actions for CI

### ISSUE THREAD

**Issue by suhr** [mathics/Mathics#870]
Travis CI is quite slow, so it would be nice to have Github Actions instead.

**Comment by GarkGarcia** [comment]
I agree. Something like [python-package-conda.yml](https://github.com/actions/starter-workflows/blob/60765e84900ccf192eadf19a9459e67566ffaabe/ci/python-package-conda.yml) could also help us address https://github.com/mathics/Mathics/issues/861 too, since [`llvmlite` can be more easily installed with Anaconda](https://github.com/numba/llvmlite#pre-built-binaries).

**Comment by GarkGarcia** [comment]
@suhr Do you consider this solved?

**Comment by rocky** [comment]
Github actions *is* a win for us. So @suhr thanks for the suggestion and for doing this. 

There is more that could be done, namely  building the Cython, or All-module, pymathics and docs variants. 

But in my opinion those could be other PRs to track each individually.

**Comment by GarkGarcia** [comment]
> But in my opinion those could be other PRs to track each individually.

Makes sense to me. @suhr Do you agree?

**Comment by suhr** [comment]
Yes. I guess I can close the issue.
