### ISSUE TITLE
Convert graphs to a pymathics module

### ISSUE THREAD

**Issue by GarkGarcia** [mathics/Mathics#888]
Failing tests regarding the `graphs` module prevented us from testing other things. For that reason, we made the decision to temporarily disable the tests from `graphs`. This should be addressed before the 1.1 release. Furthermore, we should convert `graphs` to a pymathics module so that it isn't always tested.

**Comment by rocky** [comment]
I looked at this a little bit, and while moving isn't that difficult. The whole documentation and testing process i have come to really detest. 

It was cool for a decade ago as a tour-de-force effort akin to [Knuth's Web](https://en.wikipedia.org/wiki/Web_(programming_system)) for Mathematica/Python, but nowadays there are better tools to work from. Sphinx and readthedocs is what is more prevelant and that has an [autotest](https://www.sphinx-doc.org/en/master/usage/extensions/doctest.html) that probably could be adapted to run Mathematica instead of Python. 

As I look at the existing code the problem is that there are these global varables like documentation around and work is needed just to be able to specify several "root" documents that get culled together. 

To get started when I get time to work on this, I will have to largely ditch the doc tests and go with something simpler for testing. 

By the way, something simpler for testing should also be used in the main part as well. Testing is about running all exhastive tests. Doc test is for showing how instructive *examples* work. In testing youhave a larger set of more complete but uninteresting (from the user sandpoint) of tests.

**Comment by GarkGarcia** [comment]
This was postponed to 1.2. See https://github.com/mathics/Mathics/issues/912.
