### ISSUE TITLE
failing test/test_orderless

### ISSUE THREAD

**Issue by rebcabin** [mathics/Mathics#955]
Hello -- I've been away for a couple of years, and just merged upstream master into my fork. I am very glad to see so much work and an active repo!

The merge was easy, with a few conflicts that I resolved by "blindly" taking HEAD and discarding my old fixes from two years ago. But I have one failing test. The "result" is Global`or[Global`p, Global`p], with "expected"'s being just Global`p. It seems harmless but strange and possibly not harmless in other contexts. I will dig on my own, but I thought I'd inform you. I'd appreciate a reply whether this is a known problem in master because it will help me track it down on my side if it is not a known problem in master. I skimmed the open issues and didn't see this problem, so my post may not be a duplicate.

```
@pytest.mark.parametrize('str_expr,str_expected', [
    (r'SetAttributes[or, Orderless] ; or[p, p] /. or[p_, p_] :> p', 'p'),
    (r'SetAttributes[or, Orderless] ; or[p, p, p] /. or[p_, p_] :> p', 'or[p, p, p]'),
    (r'SetAttributes[or, Orderless] ; or[p] /. or[p_, p_] :> p', 'or[p]')
])
def test_orderless(str_expr, str_expected):
    result = _evaluate(str_expr)
    expected = _evaluate(str_expected)

    assert result == expected
```

**Comment by rocky** [comment]
Hi - 

Honestly I'd like to help, but with this and wth your PR #743 I have a very hard time, both times, following what you write. Above,
in 

> The "result" is Global `or[Global`p, Global`p], with "expected"'s being just Global`p.

 it looks like some backtacks are mismatched, probably  because Mathematics uses backtick to separate the namespace from the symbols and that needs some sort of escaping in Markdown which doesn't appear above. So just figuring out which part is code text and which part isn't or where the backtick is supposed to go required effort, especially as the important symbol backtick symbol is missing. 

Also, the above pytest fragment isn't a full test, just a fragment where the _full_ test code, or where it can be found is missing.

Even allowing that I know enough to add a `import pytest` and run this via `py.test`and I know the details of how pytest's `@pytest.mark.parameterize()` works,  there's still guessing what the definition  `_evaluate()` is supposed to be.

With time and effort probably this could be figured out since the above, however complicated, is logical and follows some pattern.

But fixing other's bugs just in open-source work feels like it shouldn't have to be that hard.  What happens (and apparenlty has happened) is that people just lose interest. 

Offhand in the cavalear fashion as you are reporting this I'll say in a equal cavalier fashion that no I am not aware of a specific bug previously reported,  although I have noticed that variables seem to get displayed with their namespaces (e.g. `Global` or `System` when generally it seem more expected (and prints nicer) when the symbol is printed without the namespace. 

Whether this is a deep semantic problem or not, I don't know since I don't know Mathematica well enough.

If you can find and suggest a fix for this that'd be great. We are planning on a 1.1 release more or less after we go over documentaiton. I believe there will be a release candidate first to try to shake out the release process and catch any final low-hanging bugs. 

Lastly,  with respect to #743 any chance of turning this something that can hook into more automated test reporting schemes  (e.g. exit Mathics and set a non-zero return code in Unix terms which is what CI systems expect)?

**Comment by rocky** [comment]
Something useful I have found in the past, is to do a `git bisect` to find the commit. If this aspect works on 1.0, then there are something like 7 bisects that need to be tested. Build time is a little slow, but it is largely mechanical.

If someone finds the breaking commit, I'd like to know where it is.

**Comment by mmatera** [comment]
> Hello -- I've been away for a couple of years, and just merged upstream master into my fork. I am very glad to see so much work and an active repo!
> 
> The merge was easy, with a few conflicts that I resolved by "blindly" taking HEAD and discarding my old fixes from two years ago. But I have one failing test. The "result" is Global`or[Global`p, Global`p], with "expected"'s being just Global`p. It seems harmless but strange and possibly not harmless in other contexts. I will dig on my own, but I thought I'd inform you. I'd appreciate a reply whether this is a known problem in master because it will help me track it down on my side if it is not a known problem in master. I skimmed the open issues and didn't see this problem, so my post may not be a duplicate.
> 
> ```
> @pytest.mark.parametrize('str_expr,str_expected', [
>     (r'SetAttributes[or, Orderless] ; or[p, p] /. or[p_, p_] :> p', 'p'),
>     (r'SetAttributes[or, Orderless] ; or[p, p, p] /. or[p_, p_] :> p', 'or[p, p, p]'),
>     (r'SetAttributes[or, Orderless] ; or[p] /. or[p_, p_] :> p', 'or[p]')
> ])
> def test_orderless(str_expr, str_expected):
>     result = _evaluate(str_expr)
>     expected = _evaluate(str_expected)
> 
>     assert result == expected
> ```

Maybe this is related to the qtime fix. Indeed, Or over identical objects should reduce as in the example.

**Comment by rocky** [comment]
If you can find and fix, I'd be grateful. The full test case seems to be [here](https://github.com/rebcabin/Mathics/blob/master/test/test_evaluation.py) and it should be added once this is fixed.

**Comment by rebcabin** [comment]
Ok, I am working on the straigt repo, not a merge with my fork, and investigating. 

Apologies, I don't intend to be cavalier at all, and I do intend to be clear.  I am vitally interested in this project, and if it's more detail you need, I will provide it. I am concerned that the things I wrote are far too long ... I tire reading my own, old things. So I biased to brevity and apparently lost clarity. Please let me know what I can do to make my writing better for you!

**Comment by mmatera** [comment]
Do not worry: for me, it was clear enough. Again, the problem seems to be on the pattern matching for the "Or" function. Some weeks ago we did a  rebase and a merge of a code provided by @poke1024, with improvements in the evaluation algorithm. I guess this is a side-effect of that.  Could you confirm this, doing the test against a previous version?

**Comment by rebcabin** [comment]
I just did "make check" on the base repo (not my fork) and have 8 xfailed (which is fine). I will write a test for pattern-matching `or[_p, _p] :> p` in the base repo, avoiding any possible pollution from my two-year-old fork :)  I'll work on it a bit today.

**Comment by rebcabin** [comment]
Confirmed at the console that `or[a, a] /. {or[p_, p_] :> p}` produces 'a' as expected, so I am closing this issue. It's gotta be in my old fork.
