### ISSUE TITLE
Expression with IndentingNewLine 

### ISSUE THREAD

**Issue by rocky** [mathics/Mathics#970]
From https://github.com/jkuczm/MathematicaSyntaxAnnotations/blob/master/SyntaxAnnotations/SyntaxAnnotations.m#L280-L285

```mathematica
whitespaceQ =
	StringMatchQ[
		StringJoin[##],
		(WhitespaceCharacter | "\[IndentingNewLine]")...
	]&

```
fails to evaluate.

**Comment by mmatera** [comment]
The goal of this function (defined implicitly) is to check that each argument is a string composed just by WithespaceCharacter and \[IndentingNewLine]. The three dots at the end of the second argument represent the repetition of the previous character.
The problem is at StringMatchQ:    "..."   in WL Patters are not being properly handled. Look at
https://reference.wolfram.com/search/?q=... for details

**Comment by mmatera** [comment]
This is how WMA handles ... (RepeatedNull)
RepeatedNull[a]//FullForm
  FullForm[a...]

a...
  a...


and this is what happend with mathics:

FullForm["a"...]
   RepeatedNull["a"]

"a"...
| $RecursionLimit::reclim: Recursion depth of 200 exceeded.
     $Aborted

**Comment by rocky** [comment]
Thanks for all of the information. (Originallyl `\[IndentingLine]`was not defined, but that's been added. A separate issue has been opened for the `RepeatedNull[]` problem. 

With luck, that fixing that will also fix this. But keeping this seprate just in case it doesn't.

**Comment by mmatera** [comment]
Another thing that maybe we should solve is that still there are python exceptions that are not properly handled, and kills the interpreter. We should look at this too.

**Comment by rocky** [comment]
A lot of this has been addressed. If there is still a problem, let's open a new issue with the narrowed problem.
